version: "3"
services:
  nginx:
    image: ${nginx_image}
    container_name: ${nginx_name}
    working_dir: ${nginx_work_dir}
    ports:
      - ${nginx_bind_port_80}:80
      - ${nginx_bind_port_443}:443
      - 8443:8443
    volumes:
      - ${nginx_conf}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${nginx_confd}:/etc/nginx/conf.d/:ro
      - ${nginx_log}/:/var/log/nginx/:rw
      - ${source_dir}/:/var/www/:rw
    environment:
      TZ: ${tz}
    depends_on:
      - php
#    env_file:
#      - ../.env
    networks:
      - default

  php:
    image: ${php_image}
    container_name: ${php_name}
    working_dir: ${php_work_dir}
    volumes:
      - ${php_ini}:/usr/local/etc/php/php.ini:rw
      - ${php_fpm_conf}:/usr/local/etc/php-fpm.conf:rw
      - ${php_www_conf}:/usr/local/etc/conf.d/www.conf:rw
      - ${php_log}/:/var/log/php/:rw
      - ${source_dir}:/var/www/:rw
    environment:
      TZ: ${tz}
#    env_file:
#      - ../.env
#      - ../dc-env/.env.php73
    networks:
      - default


networks:
  default:
