version: "3"
services:
  nginx:
    image: ${nginx_image}
    container_name: ${nginx_name}
    working_dir: ${nginx_work_dir}
    tty: true
    ports:
      - ${nginx_bind_port_80}:80
      - ${nginx_bind_port_443}:443
    volumes:
      - ${nginx_conf}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${nginx_confd}:/etc/nginx/conf.d/:ro
      - ${nginx_log}/:/var/log/nginx/:rw
      - ${source_dir}/:/var/www/:rw
    environment:
      TZ: ${tz}
    networks:
      - default

networks:
  default:
