version: "3"
services:
    mysql:
      image: postgres
      container_name: dpg
      privileged: true  # 解决权限
      command: ${mysql_cmd}
      restart: always
      ports:
        - 5432:5432
      volumes:
        - ./data:/var/lib/postgresql/data/pgdata # 将数据映射到对应的路径
      environment:
        POSTGRES_PASSWORD: 123456  # 密码
        PGDATA: /var/lib/postgresql/data/pgdata # 数据存储文件夹
      networks:
        - default

networks:
  default:
